# Generated by Django 4.1.7 on 2023-03-14 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('no_candidates', models.IntegerField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.election')),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('party_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('total_votes', models.IntegerField()),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.constituency')),
            ],
        ),
    ]
