# Generated by Django 4.1.7 on 2023-03-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='candidate_symbol',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='photo',
            field=models.ImageField(upload_to='image'),
        ),
    ]
