# Generated by Django 4.1.7 on 2023-03-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_constituency_candidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
