# Generated by Django 4.1.7 on 2023-05-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_aadhar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('UID', models.CharField(max_length=12)),
                ('photo', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.DeleteModel(
            name='Aadhar',
        ),
        migrations.AddField(
            model_name='election',
            name='IsCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
